### ISSUE TITLE
Add phpgrep?

### ISSUE THREAD

**Issue by quasilyte** [ziadoz/awesome-php#1005]
I would like to propose a command-line tool for PHP code search:
https://github.com/quasilyte/phpgrep

But I was unable to figure out whether it's a good fit to this awesome-list or, if it is, in which section should I put it. Therefore, I would like to ask before sending a PR.

Thanks in advance.

**Comment by ziadoz** [comment]
@quasilyte Miscellaneous would be the section I would put it under. Please open a pull request. Thanks.
