### ISSUE TITLE
Missing TCPDF and PHPEd

### ISSUE THREAD

**Issue by lubosdz** [ziadoz/awesome-php#1013]
Hi, 

since PRs are ignored anyways, I am just noting here two critically missing items:

* PHP IDE - [PHPEd](http://www.nusphere.com/products/phped.htm) by Nusphere. I've been using it since 15 years ago, ships with excellent debugger - the only true alternative to xdebug.

* PDF generator - [TCPDF](https://github.com/tecnickcom/TCPDF) - famous since cca 10 years ago, one of first implementions of rich feature set from PDF specification.

**Comment by ziadoz** [comment]
PRs aren't ignored. Please open one for these. Thanks.
