### ISSUE TITLE
CodeIgniter is left out

### ISSUE THREAD

**Issue by otengkwame** [ziadoz/awesome-php#1113]
I've noticed that for a long time CodeIgniter has been left out from the Frameworks list. Why is it so?

**Comment by zlodes** [comment]
Because it's obsolete, written on php 5.4 (PHP 8 will be released in December).
Devs need to use modern solutions like a Symfony or Laravel.

**Comment by weirdan** [comment]
CodeIgniter 4 was released earlier this year, with 7.2 as the minimum supported PHP version. Their readme claims it's a complete rewrite, using modern practices.

**Comment by otengkwame** [comment]
@zlodes CodeIgniter is never obsolete. CodeIgniter4 has been around for a while. Even with CodeIgniter 3. I'm currently using it on PHP 7.4 engine. I think people want to still promote Laravel and Symfony but CodeIgniter is also a very good PHP Framework and in fact was an inspiration for Laravel. Please add it.

**Comment by zlodes** [comment]
@otengkwame there is PR: https://github.com/ziadoz/awesome-php/pull/1111

**Comment by rkrx** [comment]
CodeIgniter is not awesome. That's it.

**Comment by flug** [comment]
codeigniter to the merit of existing and also it allows the new developer to learn a framework and to have an MVC base and so it is good. After that, don't put all developers in the same basket, and if you think codeigniter is not crazy compared to Symfony or Laravel, don't ignore it. Be humble of the open-source dev and don't put everyone on the same level.

**Comment by weirdan** [comment]
> CodeIgniter is not awesome. That's it.

There are some non-awesome frameworks on the list already.

**Comment by otengkwame** [comment]
> @otengkwame there is PR: #1111

Great, I would be happy to see it appearing in the list. Thanks a lot

**Comment by rkrx** [comment]
> > CodeIgniter is not awesome. That's it.
> 
> There are some non-awesome frameworks on the list already.

I think that we should rather fix this instead of adding more projects to the list, which are good, but _standard_. I don't see where Codeigniter would improve the list in a meaningful way. 

Codeigniter is certainly popular and I respect that. But it also stands for old values, from which PHP (fortunately) is slowly distancing itself. And popularity alone doesn't make the awesomeness-factor of Project.

If you're looking for inspiration, you would not want to find projects like Codeigniter.

**Comment by otengkwame** [comment]
@rkrx I think you are being too harsh here. CodeIgniter4 is out there using PHP 7 so what is the "But it also stands for old values, from which PHP (fortunately) is slowly distancing itself. And popularity alone doesn't make the awesomeness-factor of Project." statement for? 

Well I guess it is up to the owner of this repo to do as he wishes.

**Comment by rkrx** [comment]
@otengkwame 
> I think you are being too harsh here.

May be. 

> CodeIgniter4 is out there using PHP 7

Support for PHP7 does not make a project awesome. CodeIgniter is still very 2005ish.

I would call a project Modern if it supports the following design principles:

- The Framework should be as invisible as possible to minimize the dependence on a specific framework. CodeIgniter still require that all controllers extend from `Controller `.
- Inversion of control / Dependency-Injection over Use of static methods (and functions).
- If I don't need all the components that CodeIgniter comes with, then I have to accept that these components are bundled. I'm now used to the fact that the individual parts of a framework don't always work well for every application and that there are often better alternatives than those that a full-featured framework brings with it.

Please do not misunderstand. CodeIgniter is supposed to be around forever and I believe that it can be the perfect framework for a large number of application concepts when ignoring more modern approaches.

I (personally) believe that this everything-included-framework-thing has worn out and that you don't need it anymore.

> Well I guess it is up to the owner of this repo to do as he wishes.
Of course.

**Comment by otengkwame** [comment]
@rkrx I agree with you. Thanks
