### ISSUE TITLE
chubbyphp/chubbyphp-framework

### ISSUE THREAD

**Issue by dominikzogg** [ziadoz/awesome-php#1114]
Is there a minimum amount of stars, downloads overall, in last month to suggest an additional microframework?
Is "Self-promotion is frowned upon" always a no go or does it only set the bar higher?

https://github.com/chubbyphp/chubbyphp-framework

- Fully tested, 100% coverage incl. infection testing.
- As minimal as i could go to fulfill the purpose.
- Everything is replaceable.
- Faster than any other PSR-15 framework (i found)

The reason why i only created a ticket, is, that if i can fulfill the criteria, but not yet, i at least know when its ok to create a PR.

**Comment by ziadoz** [comment]
@dominikzogg Sorry, but I don't think we'll be accepting any new frameworks in the near future. What we have currently covers the most popular frameworks, as well as options that offer something unique like Phalcon and Spiral.

**Comment by dominikzogg** [comment]
@ziadoz get that
