### ISSUE TITLE
Would this unit testing tips repo make sense in here? If so, where?

### ISSUE THREAD

**Issue by leonstafford** [ziadoz/awesome-php#1144]
https://github.com/sarven/unit-testing-tips

**Comment by ziadoz** [comment]
@leonstafford Thanks for the query. The content looks great. Unfortunately I removed the `Articles` section a while back because I'd noticed things become outdated quickly, and I don't want to point people to incorrect information. I'm not sure there's a place for this on the list. Sorry.
