### ISSUE TITLE
Suggestion: The Phel Language

### ISSUE THREAD

**Issue by jenshaase** [ziadoz/awesome-php#1179]
Hi,

I'm the maintainer of the Phel Language (https://phel-lang.org/). A functional programming language that compiles to PHP. Will this be a good addition to this list or is this out of scope? What will be a good section to add this?

Best regards,
Jens

**Comment by ziadoz** [comment]
@jenshaase I'd probably add this under Misc, since I can't imagine there are enough projects similar to this to open a new category, and I'm not sure where it would fit under the existing ones. Feel free to open a PR. Thanks.
