### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by thomas-price** [ziadoz/awesome-php#1189]
Suggestion for the category **Office**:
Single file PHP libraries for reading and writing Excel files
- https://github.com/shuchkin/simplexlsxgen
- https://github.com/shuchkin/simplexlsx
- https://github.com/shuchkin/simplexls
- https://github.com/shuchkin/simplecsv

**Comment by ziadoz** [comment]
Please open a PR. Thanks.
