### ISSUE TITLE
Is this list alive?

### ISSUE THREAD

**Issue by alexkart** [ziadoz/awesome-php#1231]
Is this list alive? It doesn't look like it is being updated and accepts pull requests.

**Comment by dereuromark** [comment]
I have been wondering this for a bit.

Idea:
Let's start a new list under a less bus-factor namespace (no private space), with a few collaborators that want to join in to keep the list up to date and alive.

https://github.com/php-collective/awesome-php

Feel free to push things there, maybe we can work off some of the PRs here in reverse order (newest first).

Anyone who wants to be a collaborator, ping me on the new repo (e.g. via issue)

**Comment by dereuromark** [comment]
Update:
We are still waiting to be officially switched out
In the meantime:
We are still looking for experienced and trustworthy open source devs that would be willing to help out maintain the new PHP awesome list. Please reach out there in the tickets if you feel the calling.

**Comment by ziadoz** [comment]
I haven't had the energy necessary to maintain this list for a while now. I've also had a terrible 2023, which hasn't helped.

I would like to keep this list alive and active though. @dereuromark Rather than creating and promoting fork, are you interested in being a collaborator on this repo instead?

**Comment by dereuromark** [comment]
Would that be with commit/merge rights? Then we can do it.
In general we should be >= 3 to avoid any future bus factor etc.

**Comment by ziadoz** [comment]
> Would that be with commit/merge rights? Then we can do it.

@dereuromark Yes. I've sent you an invite.

> In general we should be >= 3 to avoid any future bus factor etc.

I'm happy to bring on more people. Who is collaborating on your fork?

**Comment by alexkart** [comment]
> Who is collaborating on your fork?

Hi. I am.

**Comment by dereuromark** [comment]
We should port the changes over that we already did on the fork then.

**Comment by ziadoz** [comment]
> Hi. I am.

@alexkart I've invited you too.

If either you have any questions let me know. Thanks.

**Comment by alexkart** [comment]
> If either you have any questions let me know. Thanks.

@ziadoz
There are numerous open PRs without any responses that appear valid and eligible for merging. Are there specific reasons why they haven't been merged yet?

**Comment by dereuromark** [comment]
We need to also investigate the awesomeness of each
And usually we should have 2+ signoffs / approvals before merging

But  I agree we should start approving

**Comment by ziadoz** [comment]
> @ziadoz There are numerous open PRs without any responses that appear valid and eligible for merging. Are there specific reasons why they haven't been merged yet?

Sorry, I don't have a decision on many of the open requests. I imagine a lot of the older PRs can be closed, especially if the packages are archived, haven't been updated in several years, or aren't compatible with PHP 8.0. I've tackled a few ones I knew I planned to reject.

**Comment by alexkart** [comment]
OK, let's maybe make a rule, as @dereuromark suggested: for a PR to be merged, it must receive at least 2 approvals from the collaborators; what do you think?

**Comment by alexkart** [comment]
> I'm happy with having with two approvals for a merge, but I don't think it should be a hard requirement. Some things are obvious enough to merge (e.g. typos, broken links, formatting, package upgrades), and I trust you both to make decisions.

Yes, definitely, I meant those PRs that add new things to the list.

**Comment by alexkart** [comment]
Also, I think we can close this issue.

**Comment by ziadoz** [comment]
I've updated COLLABORATING.MD to clarify things.
