### ISSUE TITLE
Add Flight and Leaf frameworks

### ISSUE THREAD

**Issue by fadrian06** [ziadoz/awesome-php#1238]
Please add

[Flight](https://flightphp.com) and [Leaf](https://leafphp.dev) as microframeworks

**Comment by rkrx** [comment]
Both frameworks are trash.

No best practices, no preference for statically analysable code, no autowiring, nothing that Slim and other frameworks would give you already.

**Comment by fadrian06** [comment]
Yes, it may not initially encourage you to have good practices, but its simplicity means that you can apply the architecture you want, you want MVC, you can, you want hexagonal, you can...

I accept that Flight does not give you a predefined structure, but Leaf does and it would be great if more people knew about the project . Leaf is not only limited to the core, but to the Leaf MVC and Leaf frameworks  that perfectly compete with another in speed

**Comment by ziadoz** [comment]
Please open PRs not issues to add new items to the list. Thanks.
