### ISSUE TITLE
Questions: Adding PHP Graphics Libraries 

### ISSUE THREAD

**Issue by mario-deluna** [ziadoz/awesome-php#1281]
Hello Everyone,

I've just realized that the "php-collective/awesome-php" repository has been closed, but I see commits by @dereuromark here, so I'm guessing this repository is back to life. :)

I have two questions:

1. I would like to add my own project, [php-glfw](https://github.com/mario-deluna/php-glfw), to the list. It's not massively popular, but I believe it to be quite unique in the PHP ecosystem. However, I'm not sure which category it might fit into, and I'm also curious if others think it's a reasonable fit for the list at all.
2. For the php-collective repository, I created a bot that checks for old repositories and dead links. If this would be seen as still useful here, I would gladly open a PR.

I wanted to ask here first before I blindly open a PR.

Regards.

**Comment by alexkart** [comment]
Hi @mario-deluna, the awesome bot already checks for dead links, but you can add a check for old repositories.

**Comment by dereuromark** [comment]
Some of the PRs are also super old, 2019 and older.
Maybe we should also check if they released sth recently or if the project is abandoned etc.
Then we can close some of them and do some cleanup on the open PRs.

**Comment by alexkart** [comment]
> Some of the PRs are also super old, 2019 and older. Maybe we should also check if they released sth recently or if the project is abandoned etc. Then we can close some of them and do some cleanup on the open PRs.

Yes, I started reviewing the oldest PRs some time ago. Some were merged some were closed.

**Comment by raiyanreza7** [comment]
What do you need

**Comment by KingBes** [comment]
Also my project [php-webui](https://github.com/KingBes/php-webui-composer)  would like to be added to the list. Perhaps using `php` to develop desktop applications is not very popular.

**Comment by mario-deluna** [comment]
I've opend a PR for adding php-glfw here: https://github.com/ziadoz/awesome-php/pull/1309

@alexkart alright, going to open one for the last activity check separately :)
