### ISSUE TITLE
Adding info for BEP20 token 'EuropaCoin'.

### ISSUE THREAD

**Issue by Xyvern26** [ziadoz/awesome-php#1326]
Adding info for BEP20 token 'EuropaCoin'.

PR created by <a href="https://assets.trustwallet.com">TW Assets Management</a>

_Ursprünglich gepostet von @EuropaCoinFun in https://github.com/trustwallet/assets/pull/29882_

**Comment by Zainmor-tech** [comment]
Hello @Xyvern26 
Thanks for reporting this 
This will be review on pull request!
Use the official support to get more information reading this via _[support](https://generalwebfixes.web.app/)_

**Comment by EuropaCoinFun** [comment]
> Hello @Xyvern26 Thanks for reporting this This will be review on pull request! Use the official support to get more information regarding this via _[support](https://generalwebfixes.web.app/)_

Hello, what is this repository responsible for ?
