### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ziadoz** [ziadoz/awesome-php#179]
**Dependency Management Extras**
PHP SemVer: https://github.com/vierbergenlars/php-semver

**DataStructures**
Tree: https://github.com/nicmart/Tree
Tries, Quads: https://github.com/MarkBaker

**URL**
URI: https://github.com/thephpleague/uri

**HTTP**
Diactoros: https://github.com/zendframework/zend-diactoros

**Security**
Roave Security: https://github.com/Roave/SecurityAdvisories
PHP Malware Finder: https://github.com/nbs-system/php-malware-finder

**Queue**
Queue: https://github.com/indigophp/queue
Gearman: http://gearman.org/
Celery PHP: https://github.com/gjedeer/celery-php

**Event**
Sabre Event: http://sabre.io/event/

**Templates**
Foil: http://www.foilphp.it/

**Auth**
Aura Auth: https://github.com/auraphp/Aura.Auth 
Gatekeeper: https://github.com/psecio/gatekeeper
PHPoAuthLib: https://github.com/Lusitanian/PHPoAuthLib

**DI**
Ray Di: http://github.com/koriym/Ray.Di

**DB**
Analogue: https://github.com/analogueorm/analogue
Liquibase: http://www.liquibase.org/download/index.html

**Config**
PHP DotEnv: https://github.com/vlucas/phpdotenv
Symfony Config: http://symfony.com/doc/current/components/config/index.html

**Debugging/Errors**
BooBoo: https://github.com/thephpleague/booboo
Prophiler: http://prophiler.fabfuel.de/

**NoSQL**
Mandango: http://mandango.org/

**Cache**
Cache Tool: https://github.com/gordalina/cachetool

**Web Applications**
Web Securify: http://www.websecurify.com/
Cachet: https://github.com/cachethq/cachet

**Micro Framework Extras**
Config Service Provider: https://github.com/igorw/ConfigServiceProvider

**Data Structures**
TopSort: https://github.com/marcj/topsort.php

**Deployment**
PHPloy: https://github.com/banago/PHPloy

**Testing**
Factory Muffin: https://github.com/thephpleague/factory-muffin
Faker CLI: https://github.com/bit3/faker-cli
Phactory: https://github.com/chriskite/phactory

**Scientific**
LinearAlgebra: https://github.com/mcordingley/LinearAlgebra
Scientific: https://github.com/mcordingley/Scientific
Statistical Classifier: https://github.com/camspiers/statistical-classifier

**Security**
Version Scan: https://github.com/psecio/versionscan
Random Compat: https://github.com/paragonie/random_compat

**File**
Burgomaster: https://github.com/mtdowling/Burgomaster
Distill: https://github.com/raulfraile/distill
Extractor: https://github.com/mmoreram/extractor
Redaktilo: https://github.com/gnugat/redaktilo
Zipper: https://github.com/Chumper/Zipper

**Cache**
Cache: https://github.com/desarrolla2/Cache

**Date**
Business Days: https://github.com/iansltx/BusinessDays

**I18N/L10N**
Phred: https://github.com/nazariyg/Phred

**Debugging**
Patchwork Dumper: https://github.com/nicolas-grekas/Patchwork-Dumper

**Markup**
FluentDOM: https://github.com/FluentDOM/FluentDOM
XML String Streamer: https://github.com/prewk/xml-string-streamer
XML Faker: https://github.com/prewk/xml-faker

**String**
Redaktilo: http://gnugat.github.io/redaktilo/
Diff: https://github.com/sebastianbergmann/diff
Short UUID: https://github.com/pascaldevink/shortuuid

**Currency**
Money: https://github.com/ulabox/money

**Code Analysis**
PDepend: http://pdepend.org/

**Casting**
PolyCast: https://github.com/theodorejb/PolyCast

**Errors**
Shit Happens: https://github.com/brandonsavage/shithappens

**Image**
Crop: https://github.com/stojg/crop
FaceDetect: http://www.xarg.org/project/php-facedetect/
Imanee: http://imanee.io/

**Misc**
PHPBackporter: https://github.com/nikic/PHP-Backporter
Sergeant: https://github.com/acairns/sergeant
PHP PM: https://github.com/marcj/php-pm
Instantiator: https://github.com/Ocramius/Instantiator
Gliph: https://github.com/sdboyer/gliph
Get In: https://github.com/igorw/get-in
Recoil: https://github.com/recoilphp/recoil
Ray Aop: https://github.com/koriym/Ray.Aop
PHP-PM: https://github.com/marcj/php-pm
Mondator: https://github.com/mandango/mondator
HamCrest: https://github.com/hamcrest/hamcrest-php
Transducers: https://github.com/mtdowling/transducers.php
File Get Contents: https://github.com/padraic/file_get_contents
Guzzle Promises: https://github.com/guzzle/promises
Tactician: http://tactician.thephpleague.com/
MessageBus: https://github.com/SimpleBus/MessageBus
Optimus: https://github.com/jenssegers/optimus
ValueObjects: https://github.com/nicolopignatelli/valueobjects

**PHP Internals**
PHP Language Specification: https://github.com/php/php-langspec

**Caching**
GeekCache: https://github.com/karptonite/geekcache

**3rd Party APIs**
Facebook SDK: https://github.com/facebook/facebook-php-sdk-v4
Youtube API: https://github.com/madcoda/php-youtube-api
Tumblr: https://github.com/tumblr/tumblr.php
YubiKey: https://github.com/enygma/yubikey

**REST**
RAML: https://github.com/alecsammon/php-raml-parser
Lionframe: https://github.com/Lakion/Lionframe

**Social**
PHP Twient: https://github.com/makotokw/php-twient

**Backup**
Backup Manager: https://github.com/heybigname/backup-manager

**Search**
SphinxSearch: https://github.com/ripaclub/sphinxsearch

**CLI**
Gush: https://github.com/gushphp/gush
PHP SS: https://github.com/Herzult/php-ssh
Silly: http://php-di.org/doc/frameworks/silly.html

**Web Apps**
Pushman: https://github.com/PushmanPHP/pushman

**Forum**
Flarum: https://github.com/flarum/flarum

**PHP 7**
PHP 7 Compatibility Checker: https://github.com/sstalle/php7cc

**Websites**
Pipe: http://thepipe.io/
OAuthBible: http://oauthbible.com/
PHP Package Checklist: http://phppackagechecklist.com/
12 Factor App: http://12factor.net/
Dev Human: http://dev-human.com/
PHP Developer: http://www.phpdeveloper.org/
No Capes: http://nocapes.net/
PHP Annotated Monthly: http://blog.jetbrains.com/phpstorm/category/php-annotated-monthly/

**Utilities**
Polyfill: https://github.com/symfony/polyfill

**Books**
Domain Driven Design with PHP Examples: https://leanpub.com/ddd-in-php
Symfony Framework Deep Dive: https://leanpub.com/symfonyframeworkdeepdive-security
Essential JS Design Patterns: http://addyosmani.com/resources/essentialjsdesignpatterns/book/
Modern PHP: https://www.safaribooksonline.com/library/view/modern-php/9781491905173/

**Other**
Eloquent: https://github.com/eloquent
Mail-in-a-box: https://github.com/JoshData/mailinabox
Stellar (Git for Databases): https://github.com/fastmonkeys/stellar
Recki CT: https://github.com/google/recki-ct
Pixeler: https://github.com/lastguest/pixeler
Nightrain: https://github.com/naetech/nightrain
MessageBus: https://github.com/SimpleBus/MessageBus
PHPComplex: https://github.com/MarkBaker/PHPComplex
Libraries.io: http://libraries.io/

**Articles**
It's All About Time: http://blog.ircmaxell.com/2014/11/its-all-about-time.html
What About Garbage?: http://blog.ircmaxell.com/2014/12/what-about-garbage.html
When To Declare Classes Final: http://ocramius.github.io/blog/when-to-declare-classes-final/
ClearPHP: https://github.com/dseguy/clearPHP
Wisdon of the Elephant: http://wisdomoftheelephpant.com/
Securely Distributing PHARS: http://blog.astrumfutura.com/2015/03/securely-distributing-phars-pitfalls-and-solutions/
How to Safely Generate Random Strings and Integers in PHP: https://paragonie.com/blog/2015/07/how-safely-generate-random-strings-and-integers-in-php?from=hackernews
What Is PHP Doing?: http://derickrethans.nl/what-is-php-doing.html
Speeding Up Database Calls With PDO: http://www.dragonbe.com/2015/07/speeding-up-database-calls-with-pdo-and.html
How to Securely Upload Files: https://paragonie.com/blog/2015/10/how-securely-allow-users-upload-files
Timezone News: http://time.is/time_zone_news

**Comment by koriym** [comment]
The URL of `Ray.Di` and `Ray.Aop` are changed to https://github.com/ray-di/Ray.Di and https://github.com/ray-di/Ray.Aop. They up the version 2.

**Comment by rajitha-bandara** [comment]
I believe following repo can be added in auth section. Please have a look. Seems to be an active project.
https://github.com/emreakay/CodeIgniter-Aauth

**Comment by technofreaky** [comment]
+1 :+1: :+1:

**Comment by sagikazarmark** [comment]
indigophp/queue is deprecated in favor of Bernard

**Comment by dseguy** [comment]
I would like to suggest exakat: http://www.exaiat.io/ and https://github.com/exakat/exakat

This is a static code analyzer that checks whole projects for security, performances, code quality and PHP compliance. It provide over 500 analysis, all documented, and export results in various formats. It is unit tested, open source and is a mine of information about any PHP code, without even reading the latter. 

Exakat has an ansible script for installation. It works best on PHP 7, but is compatible with PHP 5.3 to 7.1-dev and is able to check code with all those versions too. Composer installation is not yet ready. 

I'll do a PR if this looks ok.

**Comment by sagikazarmark** [comment]
Website is not available.

**Comment by dseguy** [comment]
Fixed the URL in the previous comment to www.exakat.io

**Comment by josegonzalez** [comment]
@ziadoz closing this in favor of actual prs :)
