### ISSUE TITLE
CI Job for testing formatting,  testing links, ordering, ...

### ISSUE THREAD

**Issue by h4cc** [ziadoz/awesome-php#238]
How about creating a small script that will be run using Travis-Ci that could ensure the following things:

* Ensure the format is used: "[LIBRARY](LINK) - DESCRIPTION."
* Check all links for a "200 Success" Status code.
* There is a working link in the category list to the according category.
* The order in the category list is the same as in the document.
* MAYBE: Links are in alphabetic order
* MAYBE: Categories are in alphabetic order

I would volunter to start something like this if its wanted :thumbsup:

**Comment by carbontwelve** [comment]
This was something that had been created almost a year ago, is this something that is going to be implemented?

**Comment by potherca** [comment]
Bump?

**Comment by ziadoz** [comment]
@h4cc I appreciate the work you did on this, and I'm really sorry I didn't review it in a timely manner. It looks like we'll be using Travis CI and Awesome Bot to validate links going forwards. Thanks, and sorry again.
