### ISSUE TITLE
Add SupervisorPHP

### ISSUE THREAD

**Issue by sagikazarmark** [ziadoz/awesome-php#319]
It is a complete set of [Supervisor](http://supervisord.org) tools in php: xml-rpc client, config parser/builder, event listener implementation.

Link: http://supervisorphp.com

**Comment by ziadoz** [comment]
This really useful, and I'd love to add it, but there's no documentation on the website at the moment. Definitely re-submit it when you have some though.

**Comment by sagikazarmark** [comment]
Will do in the near future. Currently I am working on the underlying xmlrpc library (which might also be submitted here: fxmlrpc) After that I can refactor the codebase and write documentation.
