### ISSUE TITLE
add PHP User Agent Parsers

### ISSUE THREAD

**Issue by jakoch** [ziadoz/awesome-php#366]
- [ ] add new section for PHP User Agent Parsers
   - [browscap-php](https://github.com/browscap/browscap-php)
   - [Browscap](https://github.com/crossjoin/Browscap)
   - [ua-parser](https://github.com/ua-parser/uap-php)
   - [woothee-php](https://github.com/woothee/woothee-php)

**Comment by ziadoz** [comment]
If you create a pull request for this I'll merge it. Thanks!
