### ISSUE TITLE
Modern User Management System

### ISSUE THREAD

**Issue by mizterp** [ziadoz/awesome-php#371]
Just wanted to suggest you add: https://github.com/alexweissman/UserFrosting

**Comment by rkrx** [comment]
It's ok, but in my humble opinion, it's far away from being awesome.

* The code is somewhat [2005](https://github.com/alexweissman/UserFrosting/tree/b68f28c1051e2f76eefa2c94b5651b58fa388e5f/api)
* no composer
* functions all over the place
* sometimes used closing-tags in php-only-files ([1](https://github.com/alexweissman/UserFrosting/blob/b68f28c1051e2f76eefa2c94b5651b58fa388e5f/models/class_validator.php#L234), [2](https://github.com/alexweissman/UserFrosting/blob/b68f28c1051e2f76eefa2c94b5651b58fa388e5f/models/class.mail.php#L89), [3](https://github.com/alexweissman/UserFrosting/blob/b68f28c1051e2f76eefa2c94b5651b58fa388e5f/models/class.user.php#L99)), sometimes not.

May be it's a good project. But it's not an awesome **php**-project. Even if at some time there is no obvious problem with the code, I still get a stomachache running such a project on a server along with other projects.

**Comment by mizterp** [comment]
Totally get it! Any ideas of something similar out there that IS awesome? :)

**Comment by tleb** [comment]
[There you go](http://lmgtfy.com/?q=User+Management+System+php).

**Comment by oasisfleeting** [comment]
haha. That's what you get for trying to be clever. First result is the 
exact app he recommended.

**Comment by mizterp** [comment]
http://cdn.memegenerator.net/instances/400x/37847105.jpg

**Comment by tleb** [comment]
@oasisfleeting I understand now those statistics which says people mostly click the first link (~35%, seems like 100% in your case). If you use the scroll bar (not even needed if you want to click the 2nd link), you can find some other useful websites.

**Comment by ziadoz** [comment]
Thanks for the suggestion.
