### ISSUE TITLE
Add Workerman to Event

### ISSUE THREAD

**Issue by walkor** [ziadoz/awesome-php#387]
https://github.com/walkor/Workerman

An asynchronous event driven PHP framework for easily building fast, scalable network applications.

:-)

**Comment by nik045** [comment]
:+1:

**Comment by ecolinet** [comment]
Looks interesting, any en doc for it ?

**Comment by walkor** [comment]
@ecolinet 
[English doc](https://github.com/walkor/workerman-manual/blob/master/english/src/SUMMARY.md)

**Comment by ziadoz** [comment]
Thanks for the suggestion.
