### ISSUE TITLE
add fat free framework to micro frameworks

### ISSUE THREAD

**Issue by aslabs** [ziadoz/awesome-php#393]
It is arguably micro, but fat free for sure.
I love this framework, it really helps without too much constraints. 
Definatly awesome.

**Comment by tleb** [comment]
[Already suggested](https://github.com/ziadoz/awesome-php/issues?q=fat+free).

**Comment by aslabs** [comment]
Whats the verdict then

**Comment by UFOMelkor** [comment]
See https://github.com/ziadoz/awesome-php/pull/150#issuecomment-48866440

**Comment by aslabs** [comment]
I insist

**Comment by sn0opy** [comment]
@ziadoz what else do you need to finally add it to the list? It's the 2nd (3rd?) time you just add the suggestion-tag.

**Comment by eimajenthat** [comment]
Well, I always understood this list to be a collection of PHP things deemed awesome by @ziadoz.  It's his list, and no one else's opinion really counts.  That being said, F3 is GPLv3, where most PHP frameworks and libraries are MIT, BSD, or Apache licensed.  Those licenses give the user carte blanche to do just about anything, where the GPL (especially v. 3) places certain obligations on the user with regard to their own code which depends on the library.  If you're writing code for a client or employer, that can be a serious issue.  That's always kept me from getting into F3, although it does have some nice features.

**Comment by aslabs** [comment]
I used f3 in commercial projects. a bsd license is available in exchange of a small contribution to the project. It's reasonable and fair. 

I don't think license should make it less awesome.

**Comment by ziadoz** [comment]
Thanks for the suggestion, but I've no plans to add F3 at the moment.

**Comment by ethanpil** [comment]
+1 Fat Free
