### ISSUE TITLE
missing CodeIgniter?

### ISSUE THREAD

**Issue by xenogenesi** [ziadoz/awesome-php#423]
Frameworks: http://www.codeigniter.com

**Comment by tleb** [comment]
I think [CodeIgniter is a suggestion](https://github.com/ziadoz/awesome-php/issues?utf8=✓&q=codeigniter).

**Comment by xenogenesi** [comment]
Sorry I didn't seen the suggestion.
I'd like also to suggest [bonfire](https://github.com/ci-bonfire/Bonfire) and even better [sprintphp](https://github.com/ci-bonfire/Sprint), both are *frameworks* over CodeIgniter to add various (IMHO essential) *tools*
