### ISSUE TITLE
Possible new section

### ISSUE THREAD

**Issue by NigelGreenway** [ziadoz/awesome-php#437]
One thing that I have found handy is certain people to follow on Twitter/Github and so on.

So, I wondered if it would be worth having a section on awesome contributors to the community for people wanting to better themselves?

**Comment by dupuchba** [comment]
:+1: on that but it should be warned that it's very opinionated obviously.

**Comment by ziadoz** [comment]
I actually have this idea on my enhancements list (https://github.com/ziadoz/awesome-php/issues/46), but I'm not sure if/when this will happen. There are various issues which would need to be addressed first, such as people contacting community members because they're on this list etc.
