### ISSUE TITLE
sentry => sentinel

### ISSUE THREAD

**Issue by lorvent** [ziadoz/awesome-php#473]
please replace sentry with sentinel

cartalyst.com/manual/sentinel/2.0

also a typo for 
PHPPowerPoint - A library for working with Microsoft Word documents. => PHPPowerPoint - A library for working with Microsoft Powerpoint presentations.

**Comment by tleb** [comment]
Wouldn't [cartalyst.com/manual/sentinel/](cartalyst.com/manual/sentinel/) be more future-proof?

**Comment by lorvent** [comment]
Yes

That would be more future proof since v3 is around the corner

**Comment by ziadoz** [comment]
@lorvent Could you please make a pull request with the change in. Thanks.
