### ISSUE TITLE
Compat section

### ISSUE THREAD

**Issue by sagikazarmark** [ziadoz/awesome-php#509]
I propose having a section for compatibility/backport packages. Although it is not recommended to use "legacy" PHP versions, we all know that it is rarely up to the developers.

Libraries that could go into the compat section:

https://github.com/ircmaxell/password_compat (already listed in the Passwords section)
https://github.com/ramsey/array_column/
https://github.com/indigophp/hash-compat
https://github.com/imnotjames/curlfile-compat
https://github.com/paragonie/random_compat
https://github.com/symfony/polyfill

**Comment by ziadoz** [comment]
That's a great idea. If you make a pull request I'll merge it. Thanks.

**Comment by sagikazarmark** [comment]
Actually, I've contacted @ircmaxell, @ramsey, @paragonie if they want to create a common organization for these kind of packages (I maintain hash-compat).

Let's see if they respond to that. If not, I will make a pull request, if yes, then we could probably wait for that.

**Comment by ramsey** [comment]
I'd add https://github.com/jakeasmith/http_build_url to that list. It's come in handy for me. :-)

**Comment by sagikazarmark** [comment]
Great. Pinging @jakeasmith to include in the discussion and involve in the organization idea.

**Comment by jakeasmith** [comment]
Thanks for the ping. Listing these types of packages together is definitely a great idea and I'd be open to discussing a common organization for grouping them together. Feel free to email me directly about it at theman@jakeasmith.com

**Comment by ziadoz** [comment]
I'm going to close, but let me know if you do decide you want to add the category as originally proposed, as I'll gladly take a look.
