### ISSUE TITLE
Add Codeigniter to framework list

### ISSUE THREAD

**Issue by amitkverma** [ziadoz/awesome-php#514]

**Comment by tleb** [comment]
[Please](https://github.com/ziadoz/awesome-php/issues?q=codeigniter).

**Comment by jacobsantos** [comment]
It is funny when half the tickets are asking to add CodeIgniter.

**Comment by chiqui3d** [comment]
+1 a codeigniter

**Comment by tleb** [comment]
@jacobsantos I think we should add an issue because Codeigniter is missing.
