### ISSUE TITLE
i have an RPC

### ISSUE THREAD

**Issue by xcl3721** [ziadoz/awesome-php#516]
may i joint my project to the list?
https://github.com/xcl3721/Dora-RPC

php swoole exntesion RPC 
under dev
working for php distribute backend RPC support
sorry my poor english

**Comment by bocharsky-bw** [comment]
It'll be nice to have an English docs in your project

**Comment by xcl3721** [comment]
i see.i will try to find some one help.

**Comment by ziadoz** [comment]
Feel free to make a pull request when you're ready. Thanks.
