### ISSUE TITLE
Point people into PHP 7 way

### ISSUE THREAD

**Issue by mirfilip** [ziadoz/awesome-php#627]
More and more people come here to find the building blocks for their new project. Some of them are not aware of php7 being out and getting more stable with every release.

I suggest two things:
* [ ] Adding a section describing why one should use php7 instead of php5. Benchmarks, new features articles etc. could come here.
* [ ] Adding a `PHP 7` ready marker to existing list of packages

**Comment by josegonzalez** [comment]
Isn't all php 5 code php7 code?

**Comment by mirfilip** [comment]
[No, it isn't](http://php.net/manual/en/migration70.incompatible.php). But that wasn't my point. If I were a newcomer to a php world, visiting this should point me to a state of the art stuff. It already is an awesome resource, don't get me wrong, but we should point people to what has been a huge overhaul of the language.

Consider starting a project from the stratch. I imagine you'd at least want to be alerted of the benefits of the new version of the language.

**Comment by josegonzalez** [comment]
Two things:

- Happy to add articles pointing to how much better php7 is than php5. Feel free to PR those as you come across them.
- We don't add markers to any other package for anything, so I'm not on board with this. We'll get people asking if there are Laravel Facades or Symfony extensions if we added little badges. Ideally *all* the code here either targets the latest PHP7 release or works well under it. I don't see a need to specifically point out those packages.

**Comment by mirfilip** [comment]
Fair enough. I come back to this list when I need to start a project in the new field and did so recently, but with php7 in mind. I needed to check the packages for php7 compliance (the reality is unfortunately far from your statement :() one-by-one and just thought that would help people.

I will surely gather some good resources but let's wait for others to have their take.

**Comment by josegonzalez** [comment]
Maybe worth starting a "php7 badge" movement.
