### ISSUE TITLE
php.libhunt.com

### ISSUE THREAD

**Issue by StanBright** [ziadoz/awesome-php#633]
Hi guys, 

Please, accept my apologies if this isn't the best place to post this.

I released a website today that is based on the "awesome-php" list - http://php.libhunt.com. It adds some additional value - like ordering projects by popularity and showing their activity. I believe this helps when researching for a new lib. Do you think it will be valuable to readers of "awesome-php" to add php.libhunt.com to the description of this repo?

Thanks,
Stan

**Comment by kamilsk** [comment]
awesome! thank you!

**Comment by ziadoz** [comment]
@StanBright Thanks for the offer. Although I can appreciate the amount of effort it's taken you to build this, it isn't something I'd be interested in linking to. 

I'm not a fan of the numerous attempts to bring all awesome lists under a single network. Each project is run by different people with different goals, and in some cases a website of their own already (e.g. Awesome Ruby). Projects like this just cause confusion. I'm also not keen on profitting off of what is essentially a curated list of other people's hard work with product and job advertisements either. 

That being said, I wish you the best of luck.

**Comment by StanBright** [comment]
I understand. Thanks for the kind words, anyway! I really believe that LibHunt brings usefulness to the community.

**Comment by josegonzalez** [comment]
@StanBright would also be pretty pro if you delisted the php version, or at least made it based on some other list, as per the wishes of this repo's owner :)
