### ISSUE TITLE
Some more Frameworks to Consider

### ISSUE THREAD

**Issue by trentramseyer** [ziadoz/awesome-php#687]
Codeigniter 
https://codeigniter.com/

Fat-Free
https://fatfreeframework.com/home

FuelPHP
http://fuelphp.com/

Nova  (fomally Simple MVC)
http://novaframework.com/php-framework

PHPixie
https://phpixie.com/

**Comment by mablae** [comment]
This collection is not meant to be complete, but show the awesome ones only. 

Hence the title of the repo.

**Comment by josegonzalez** [comment]
Basically what @mablae said.
