### ISSUE TITLE
Remove phpdbg

### ISSUE THREAD

**Issue by ReadmeCritic** [ziadoz/awesome-php#835]
http://phpdbg.com/ `Connection timed out - connect(2) for "phpdbg.com" port 80` at line 430

**Comment by greveritt** [comment]
I think the reason the site is down is that phpdbg was integrated into PHP itself. With that said, you need to enable phpdbg at compile time and http://phpdbg.com/ is the only official documentation that is listed on PHP.net as far as I can tell: http://php.net/manual/en/migration56.new-features.php#migration56.new-features.phpdbg

**Comment by mfdj** [comment]
The link could probably the php.net docs, which should be the canonical home according to the the author of phpdbg https://twitter.com/Ocramius/status/665795770214449152

https://www.reddit.com/r/PHP/comments/5zmis5/is_phpdbg_dead/ does indicate it's a stable but maybe a little dormant (on the docs front certainly).

**Comment by Bilge** [comment]
Since the site is still down I think we can assume it's not coming back.

**Comment by ziadoz** [comment]
PHPDBG was removed from the list a couple of months ago. Thanks for letting us know.
