### ISSUE TITLE
Library sugestion: MakeAccessible

### ISSUE THREAD

**Issue by e200** [ziadoz/awesome-php#855]
https://github.com/e200/MakeAccessible

A library that helps test encapsulated code.

**Comment by ziadoz** [comment]
@e200 It'd be good if you could open a proper PR for this, thanks.

**Comment by e200** [comment]
Something is wrong with your Bot, I'm not seeing the problem, so I'm not seeing how to solve it, I already have a pull request, but it's being marked as invalid by Travis. Whats going on?

**Comment by ziadoz** [comment]
@e200 Rebase your branch and it should build fine.
