### ISSUE TITLE
Any active maintainers?

### ISSUE THREAD

**Issue by Bilge** [ziadoz/awesome-php#870]
Seems the last PR was merged [two months ago](https://github.com/ziadoz/awesome-php/pull/846), and the one before that, [four moths ago](https://github.com/ziadoz/awesome-php/pull/834). Does this project need more maintainers? Or otherwise, what's the plan here?

**Comment by m1guelpf** [comment]
@ziadoz If it needs more mantainers, maybe I can also help :smile:

**Comment by ziadoz** [comment]
@Bilge Yes, we're active. I try to pick things up when I can, which admittedly isn't as often as I'd like, but @josegonzalez tends to merge things quite often. I'm not sure what @jadb's current status is. Anyone wanting to help out should email me, which is mentioned in the collaborator file.

We only merge things that meet the contribution guidelines and that we feel make sense on the list when we've had a chance to review them. At some point I intend to go and close PRs that aren't going to be merged, but I can't say exactly when that will be at the moment, sorry.
