### ISSUE TITLE
Lots of outdated, unmaintained projects

### ISSUE THREAD

**Issue by antonmedv** [ziadoz/awesome-php#886]
Really hard to call more then half of projects as awesome. They are outdated, or unmaintained projects. 
Maybe it's time to review all awesome-php list? Or rename it to list-of-software-releated-to-php.
Not it's really hard to give link to this list and call it awesome.

Thanks! I did not mean to offend anyone.

**Comment by josegonzalez** [comment]
Pull requests welcome!

**Comment by ziadoz** [comment]
I've been working on a script to remove outdated libraries, so once it's finished I'll clean things up. In the meantime though, pull requests are welcome.

**Comment by rsn130153** [comment]
R4hh5ymujyyuhhhhhhhh5hjn5m5yh4hmmmhmmmhmh55uml6

Em 4 de jan de 2018 09:18, "Anton Medvedev" <notifications@github.com>
escreveu:
