### ISSUE TITLE
Mongo library

### ISSUE THREAD

**Issue by eman1986** [ziadoz/awesome-php#926]
I wrote a thin ORM-ish library for mongoDB.

https://github.com/eman-development-design/Leaf-Orm

I'm looking to get some exposure on it, it was something I wrote for a project and figured others could benefit from it.

**Comment by josegonzalez** [comment]
From our contributing docs:

> Self-promotion is frowned upon, so please consider seriously whether your project meets the criteria before opening a pull request, otherwise it may be closed without being reviewed.

There are other, well-known mongodb ORMs out there. Thanks for your contribution, but at this time we won't be accepting it.

**Comment by eman1986** [comment]
I'm sorry for not reading that first.

> There are other, well-known mongodb ORMs out there.

theres only one and its vastly outdated and super clunky, thats why I wrote my own.

but rules are rules, I find another venue to promote my library, best of luck with your list.
