### ISSUE TITLE
LazyRecord is a historical repo

### ISSUE THREAD

**Issue by happycoder97** [ziadoz/awesome-php#973]
LazyRecord's repo discription says:
>The fast ORM for PHP. (This is a history repo, please visit maghead/maghead) 

Should we replace it with https://github.com/maghead/maghead?

**Comment by happycoder97** [comment]
Cool :)

**Comment by ziadoz** [comment]
Thanks for opening a PR. https://github.com/ziadoz/awesome-php/pull/974
